spring:
  data:
    mongodb:
      uri: mongodb://springaidemo:pass@springaidemo-mongo:27017
  ai:
    vectorstore:
      qdrant:
        host: springaidemo-qdrant
        port: 6334
        collection-name: springaidemo
        initialize-schema: true

logging:
  level:
    org.springframework.ai: DEBUG
    io.qdrant: DEBUG
