spring:
  data:
    mongodb:
      uri: mongodb://springaidemo:pass@localhost:27017/springaidemo?authSource=springaidemo
  ai:
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: springaidemo
        initialize-schema: true

logging:
  level:
    org.springframework.ai: DEBUG
    io.qdrant: DEBUG
