spring:
  ai:
    ollama:
      init:
        embedding:
          include: false
      chat:
        options:
          model: llama3.1:8b
      embedding:
        model: nomic-embed-text:v1.5

app:
  etl:
    ignored-paths:
      - .git
      - .idea
      - .vscode
      - build
      - dist
      - node_modules